### PR TITLE
Fix crash on latest MacOS version.

### PR DESCRIPTION
**Pull request by jpd236**
- Update wxWidgets to 3.1.5 to fix https://trac.wxwidgets.org/ticket/19100
- wxWidgets 3.1.5 drops support for MacOS < 10.10, so bump to that minimum
- Remove obsolete wxWidgets patch

### CODE REVIEW

**Comment by jpd236** [comment]
Gave this a cursory test on Windows and Mac and it seems to at least be basically functional, though there may be trickier bugs under the covers.

The Mac UI is a bit different now, particularly with the toolbar. It looks off to me - I think the icons are probably 2x the size they're supposed to be, and it's odd that they're level with the window title now as opposed to below it, but I'm guessing this is meant to match newer Mac style better?

**Comment by mrichards42** [comment]
Will take a look at this in combination with my wxlua3 branch. My attempts at this without upgrading wxLua all failed with

```
./lua/wxbind/src/wxcore_event.cpp:2808:33: error: no matching constructor for initialization of 'wxPaintEvent'
    wxPaintEvent* returns = new wxPaintEvent(id);
```

**Comment by jpd236** [comment]
Yep, this PR is against the wxlua3 branch rather than the master branch for the same reason.

**Comment by mrichards42** [comment]
So it is :)

**Pull request merged**
